name: PlatformIO Build
run-name: ${{ github.ref }}
on: [push]
jobs:
  Build-Executable:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1.0.0
