name: PlatformIO Build & Test
run-name: PlatformIO Build & Test
on: [pull_request]
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1.0.0
      - name: Run Tests
        run: platformio test -e native -vvv
