name: PlatformIO Build
run-name: ${{ github.ref }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1.0.0
